# Generated by Django 4.2.3 on 2023-07-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('email', models.EmailField(max_length=60)),
                ('profile_pic', models.ImageField(upload_to='')),
            ],
        ),
    ]
