# Generated by Django 4.2.3 on 2023-07-27 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
